# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

############################

# default_platform(:ios)

# platform :ios do
#   desc "Description of what the lane does"
#   lane :custom_lane do
#     # add actions here: https://docs.fastlane.tools/actions
#   end
# end

############################

default_platform(:ios)

platform :ios do
  lane :test_ci do
    run_tests(
      workspace: "Showcase.xcworkspace",
      scheme: "App",
      destination: "platform=iOS Simulator,name=iPhone 15",
      clean: true
    )
  end

  lane :build_ci do
    build_app(
      workspace: "Showcase.xcworkspace",
      scheme: "App",
      clean: true
    )
  end
end